version: "3"
services:
  pub:
    build:
      context: .
      dockerfile: pub/Dockerfile
    ports:
     - "5000:5000"
    volumes:
     - ./pub:/build
    command:  uwsgi --socket 0.0.0.0:5000 --protocol=http -w app:app --gevent 2000 --workers 5
    # command: gunicorn pub.app:app --worker-class gevent --bind 0.0.0.0:5000 --worker-connections=2000 --workers=5
    depends_on:
     - redis
  redis:
    image: redis
    ports:
     - "6380:6379"
    expose:
     - 6380

  nginx:
    build: ./nginx
    restart: always
    volumes:
      - /www/static
    ports:
      - "82:80"
    depends_on:
      - pub

